name: Validate Model Submissions

on:
  pull_request:
    paths:
      - "models/**"
      - ".github/scripts/**"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema requests unittest-xml-reporting

      - name: Test validation script
        run: |
          cd .github/scripts
          python -m unittest discover -v

      - name: Validate model metadata
        run: |
          python .github/scripts/validate_models.py
